### PR TITLE
Run Kafka tests against 3.1.0

### PR DESCRIPTION
**Pull request by teozkr**
## Description
See https://github.com/stackabletech/kafka-operator/issues/309

## Review Checklist
- [ ] Code contains useful comments
- [ ] Changelog updated (or not applicable)

### CODE REVIEW

**Comment by teozkr** [comment]
Do we want to keep testing against 2.8.1 as well? Is there a way that we can/want to set up matrix tests here?

**Comment by maltesander** [comment]
> Do we want to keep testing against 2.8.1 as well? Is there a way that we can/want to set up matrix tests here?

I think we should. If the operator supports both versions we should test against both? We probably need to implement / discuss the version support matrix stuff again? @backstreetkiwi what do you think?

**Comment by backstreetkiwi** [comment]
> > Do we want to keep testing against 2.8.1 as well? Is there a way that we can/want to set up matrix tests here?
> 
> I think we should. If the operator supports both versions we should test against both? We probably need to implement / discuss the version support matrix stuff again? @backstreetkiwi what do you think?

We have to discuss it, I was approached by the superset devs today as well w/ the same topic. Architecture board?

**Comment by maltesander** [comment]
> > > Do we want to keep testing against 2.8.1 as well? Is there a way that we can/want to set up matrix tests here?
> > 
> > 
> > I think we should. If the operator supports both versions we should test against both? We probably need to implement / discuss the version support matrix stuff again? @backstreetkiwi what do you think?
> 
> We have to discuss it, I was approached by the superset devs today as well w/ the same topic. Architecture board?

yeah, teo put it already.

**Pull request merged**
