### PR TITLE
Convert create_test_cluster to Python

### PR DESCRIPTION
**Pull request by lfrancke**
## Description

This converts `create_cluster_test.sh` to Python because error handling and ergonomics in the bash script weren't great and I don't know bash well enough to improve it.

This will also incorporate the changes from #52 

## Review Checklist
- [x] Code contains useful comments
- [x] Changelog updated (or not applicable)

### CODE REVIEW

**Comment by lfrancke** [comment]
@hikhvar This is my followup PR - it's still in draft state but I want to finish it soon

**Comment by lfrancke** [comment]
This is missing an updated readme and the removal of the old bash version.
I forgot about both and will add that but the script itself should be ready to be reviewed

**Review by razvan — APPROVED** [review]
Works.

**Review by razvan — APPROVED** [review]
I think it's enough that the env vars are written to the console. Other Helm charts (eg. Postgresql) take the same approach.

**Pull request merged**
