### PR TITLE
Create integration tests for the hbase-operator

### PR DESCRIPTION
**Pull request by siegfriedweber**
## Description

Integration tests for the HBase operator created.

## Review Checklist
- [x] Code contains useful comments
- [x] Changelog updated (or not applicable)

### CODE REVIEW

**Review by razvan — APPROVED** [review]
Nice work. Tested with the rework branch in the hbase-operator repo.

**Comment by backstreetkiwi** [comment]
A test run using this branch and the binary `0.2.0-pr110` was successful.

**Review by razvan — APPROVED** [review]
Tested again and still looking good.

**Comment by backstreetkiwi** [comment]
@siegfriedweber I cannot activate the nightly test against `*-nightly` until https://github.com/stackabletech/hbase-operator/pull/110 is merged, right?

**Pull request merged**
