### PR TITLE
Adapt Kafka tests for STFU rework

### LINKED ISSUE #77: Eliminate dependencies on duplicate
https://github.com/Emoun/duplicate/issues/42 makes duplicate 0.3.0 incompatible with SNAFU 0.7.0, and https://github.com/Emoun/duplicate/issues/43 implies that the situation is likely to return in the future.

### PR DESCRIPTION
**Pull request by teozkr**
## Description
Also fixes #77, since that was blocking this PR.

Pending issues:

- [x] https://github.com/stackabletech/kafka-operator/issues/273 (workaround: `kubectl create rolebinding kafka --clusterrole=view --serviceaccount=default:default`)
- [x] https://github.com/stackabletech/kafka-operator/issues/274 (not strictly a blocker, but slows the tests down)
- [x] https://github.com/stackabletech/kafka-operator/pull/271

## Review Checklist
- [ ] Code contains useful comments
- [ ] Changelog updated (or not applicable)

### CODE REVIEW

**Review by backstreetkiwi — APPROVED** [review]
Test runs fine in Jenkins: https://ci.stackable.tech/view/02%20Component%20Tests%20(flex)/job/Kafka%20Operator%20Integration%20Tests%20(flex)/26/

**Comment by backstreetkiwi** [comment]
@teozkr The test runs fine so I approved. If you need further approval due to the fact that there is also Rust code involved, we can wait for a developer to approve, otherwise I'm fine with merging it like this.

**Comment by teozkr** [comment]
Hopefully nothing here should be controversial, it's generally just the minimum viable change to get things up and running again.

bors r+

**Comment by teozkr** [comment]
Ah, right, heh.. :P

**Pull request merged**
