### PR TITLE
access_services.py: downgrade kubernetes lib due to bug

### PR DESCRIPTION
**Pull request by sbernauer**
## Description
For https://github.com/stackabletech/integration-tests/issues/186

## Review Checklist
- [ ] Code contains useful comments
- [ ] Changelog updated (or not applicable)

### CODE REVIEW

**Review by maltesander — APPROVED** [review]
LGTM.

**Comment by teozkr** [comment]
Do we want to ship a known-good environment for all of these scripts (Poetry, Pipenv, Nix, whatever)?

**Comment by sbernauer** [comment]
> Do we want to ship a known-good environment for all of these scripts (Poetry, Pipenv, Nix, whatever)?

To be honest i don't have an opinion. Never have used any of those.

**Review by soenkeliebau — APPROVED** [review]

**Comment by soenkeliebau** [comment]
> Do we want to ship a known-good environment for all of these scripts (Poetry, Pipenv, Nix, whatever)?

I think we'll need to do that at some point in time, I recently discussed this with Malte [here](https://groups.google.com/a/stackable.de/g/external-developers) as well. We might be able to get away without for a little while longer, but not sure how long tbh.

I love the idea of Nix, not sure how much acceptance is out there for it though, so we might want to look at pipenv or something similar first and ship a Nix config as an add-on.

**Comment by lfrancke** [comment]
(none of the things I mentioned should block this particular PR)

**Comment by sbernauer** [comment]
Thanks for your feedback, should i open a follow-up ticket for this? The question is if it will remain a python script or it will be ported to e.g. Rust. I would depend the venv/nix question on that decision.

**Pull request merged**
