### PR TITLE
Instruct the create_test_cluster to reuse an existing kubernetes cluster

### PR DESCRIPTION
**Pull request by hikhvar**
## Review Checklist
- [x] Code contains useful comments
- [x] Changelog updated (or not applicable)

### CODE REVIEW

**Comment by lfrancke** [comment]
Hi @hikhvar, I actually got fed up with bash when trying to add error handling so I'm working on a PR for a Python version of this script. I'll make sure to include your PR into it if you're fine with that?

**Comment by hikhvar** [comment]
I will be fine with that! However, in my current setup I don't use this script anymore. I got fed up with bash, too. As a consequence I dropped this approach.

**Comment by lfrancke** [comment]
Great, I'll ping you when the PR is up and will close this one?

**Comment by backstreetkiwi** [comment]
@hikhvar , @lfrancke Can I delete the branch behind this PR? I'm cleaning up the repo a bit...

**Comment by lfrancke** [comment]
Yes, this is implemented.

**Pull request closed without merging**
