### PR TITLE
Remove ZooKeeper tests

### PR DESCRIPTION
**Pull request by siegfriedweber**
## Description

The ZooKeeper tests were moved to the zookeeper-operator repository (see stackabletech/zookeeper-operator#464).

It is probably necessary to adapt the CI pipeline.

## Review Checklist
- [x] Code contains useful comments
- [x] Changelog updated (or not applicable)

### CODE REVIEW

**Comment by maltesander** [comment]
Should we wait with merging this until @backstreetkiwi had a look at the pipeline and we have tests running from the operators?

**Comment by backstreetkiwi** [comment]
> Should we wait with merging this until @backstreetkiwi had a look at the pipeline and we have tests running from the operators?

If you don't wait the tests will fail. I can have a look at it next week if it helps...

**Comment by backstreetkiwi** [comment]
It looks like the `.ci` folder has not been migrated in https://github.com/stackabletech/zookeeper-operator/pull/464 (paging @siegfriedweber )

**Comment by backstreetkiwi** [comment]
It looks like the `.ci` folder has not been migrated in https://github.com/stackabletech/zookeeper-operator/pull/464 (paging @siegfriedweber )

> > It looks like the `.ci` folder has not been migrated in [stackabletech/zookeeper-operator#464](https://github.com/stackabletech/zookeeper-operator/pull/464) (paging @siegfriedweber )
> 
> At least the `test.sh` file in the `.ci` folder must be adapted to work in the new location. Instead of guessing and not being able to try it out, I thought to leave this work to our CI expert.

I'm glad to hear you finally found one. I look forward to meet her or him ;-)

**Comment by backstreetkiwi** [comment]
Okay, @siegfriedweber, I had a look at the tests in `zookeeper-operator` repo and now I understand your point. It is not just a move to another repo but instead the whole templating stuff is new (at least to me). I think I will try that out running the testdriver locally instead of on Jenkins...

**Review by backstreetkiwi — APPROVED** [review]
LGTM, Jenkins no longer uses this test.

**Pull request merged**
