### PR TITLE
Remove commons and cargo references.

### PR DESCRIPTION
**Pull request by razvan**
## Description

Remove the commons Rust library since the integration tests now use kuttl.

### CODE REVIEW

**Review by maltesander — COMMENTED** [review]
LGTM. Lets wait for airflow https://github.com/stackabletech/integration-tests/pull/133 though?

**Comment by backstreetkiwi** [comment]
@razvan Will the dependabot be switched off automatically when the Rust stuff is gone or do we have to take care of that, too?

**Comment by razvan** [comment]
> @razvan Will the dependabot be switched off automatically when the Rust stuff is gone or do we have to take care of that, too?

Yes it will be automatically removed for the cargo ecosystem. It stays for the GH actions.

**Review by maltesander — APPROVED** [review]
LGTM.

**Pull request merged**
