### PR TITLE
Rework druid operator

### PR DESCRIPTION
**Pull request by fhennig**
## Description

Adapt the test to the new zk/druid version

## Review Checklist
- ~Code contains useful comments~
- ~Changelog updated (or not applicable)~

### CODE REVIEW

**Comment by fhennig** [comment]
This has a dependency on the zookeeper CRD, so to not reference the branch a zookeeper release needs to be made.

**Review by siegfriedweber — CHANGES_REQUESTED** [review]
LGTM

Can be merged when stackabletech/druid-operator#59 is merged and the dependency is adapted.

**Review by maltesander — COMMENTED** [review]
Doesnt work for me:
```
     Running tests/create_cluster.rs (/home/malte/developer/workspace/integration-tests/target/debug/deps/create_cluster-128c8d8ae64e0e42)

running 1 test
test test_create_1_cluster_0_22_0 ... [ZookeeperCluster/test-druid-zk-77199557] Waiting for [1/1] pod(s) with extra labels {"app.kubernetes.io/version": "3.5.8"} to be ready...
[ZookeeperCluster/test-druid-zk-77199557] Installation finished
[DruidCluster/simple-2503321758] Waiting for [5/5] pod(s) with extra labels {"app.kubernetes.io/version": "0.22.0"} to be ready...
[DruidCluster/simple-2503321758] Installation finished
thread 'main' panicked at 'Resource could not be created: ApiError: Service "druid-router" is invalid: spec.ports[0].nodePort: Invalid value: 30888: provided port is already allocated: Invalid (ErrorResponse { status: "Failure", message: "Service \"druid-router\" is invalid: spec.ports[0].nodePort: Invalid value: 30888: provided port is already allocated", reason: "Invalid", code: 422 })

Caused by:
    Service "druid-router" is invalid: spec.ports[0].nodePort: Invalid value: 30888: provided port is already allocated: Invalid', commons/src/test/kube.rs:126:18
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[DruidCluster/simple-2503321758] Waiting for 5 Pod(s) to terminate
[ZookeeperCluster/test-druid-zk-77199557] Waiting for 5 Pod(s) to terminate
[ZookeeperCluster/test-druid-zk-77199557] Waiting for 4 Pod(s) to terminate
[ZookeeperCluster/test-druid-zk-77199557] Waiting for 4 Pod(s) to terminate
[ZookeeperCluster/test-druid-zk-77199557] Waiting for pod termination delay : 5s ...
FAILED

failures:

failures:
    test_create_1_cluster_0_22_0

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 121.90s

```

**Review by maltesander — DISMISSED** [review]
LGTM.

**Review by maltesander — DISMISSED** [review]
LGTM.

**Comment by fhennig** [comment]
bors merge

**Review by maltesander — APPROVED** [review]
LGTM.

**Pull request merged**
